name: CI/CD Pipeline

on:
  push:
    branches:
      - stage  # Trigger on pushes to the stage branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Adjust this to match your project requirements

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build and deploy to GCP Cloud Run
        env:
          GCP_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          echo "${{ secrets.GCP_CREDENTIALS }}" | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project $GCP_PROJECT
          gcloud --quiet config set run/region us-central1
          gcloud --quiet builds submit --tag gcr.io/$GCP_PROJECT/app-image
          gcloud --quiet run deploy stage-app --image gcr.io/$GCP_PROJECT/app-image --platform managed --region us-central1 --allow-unauthenticated
